[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window]
opacity = 0.95
padding = { x = 10, y = 10 }

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12.0

[terminal.shell]
program = "/usr/bin/zsh"
